repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^(uav_control/)
      - id: end-of-file-fixer
        files: ^(uav_control/)
      - id: check-yaml
        files: ^(uav_control/)
      - id: check-added-large-files
        files: ^(uav_control/)

  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: v5.10.1
  #   hooks:
  #     - id: isort
  #       files: ^(uav_control/)

  # - repo: https://github.com/psf/black
  #   rev: 23.7.0
  #   hooks:
  #     - id: black
  #       language_version: python3.9
  #       files: ^(uav_control/)
