[tool.black]
line-length = 100
target-version = ['py37', 'py38']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.nox
  | \.tox
  | \.pyenv
)/
'''